Endpoints
germansanz93/Spotify-Service pull request #2
Opened 2021-11-04 21:30 UTC by germansanz93

Cree las validaciones y la coleccion  de postman, la cual voy a ir actualizando cuando vaya terminando los endpoints. Tengo los endpoints de Album y Track.

2021-11-05 14:33 UTC, mrojasabregu requested changes
Resolve los comentarios que te hice.

Y me gustaría que agregues logs usando slf4j

2021-11-05 14:33 UTC, mrojasabregu commented on spotify-service/src/main/java/com/pinapp/spotifyservice/controller/AlbumController.java
> +  @PostMapping(path = "/")
el path="/" no es necesario en este caso, podes poner @PostMapping solamente

2021-11-05 14:33 UTC, mrojasabregu commented on spotify-service/src/main/java/com/pinapp/spotifyservice/controller/AlbumController.java
>  @RequestMapping(path = "/albums")
acá seria en singular, album

2021-11-05 14:33 UTC, mrojasabregu commented on spotify-service/src/main/java/com/pinapp/spotifyservice/controller/ArtistController.java
>    @GetMapping(path = "/")
no es necesario el /

2021-11-05 14:33 UTC, mrojasabregu commented on spotify-service/src/main/java/com/pinapp/spotifyservice/controller/ArtistController.java
>  @RestController
es en singular

2021-11-05 14:33 UTC, mrojasabregu commented on spotify-service/src/main/java/com/pinapp/spotifyservice/controller/ArtistController.java
> +  @PostMapping(path = "/")
no es necesario el "/"

2021-11-05 14:33 UTC, mrojasabregu commented on spotify-service/src/main/java/com/pinapp/spotifyservice/service/AlbumService.java
> +//  @Qualifier("albums")
no debemos subir codigo comentado

2021-11-05 14:33 UTC, mrojasabregu commented on spotify-service/src/main/java/com/pinapp/spotifyservice/service/ArtistService.java
> +    Artist artist = artists.stream().filter(a -> a.getIdArtist() == id)
no es necesario crear el objeto artist
 directamente podrias poner 

return artists.stream()
.filter(a -> a.getIdArtist() == id)
.findFirst()
.orElse(null);

2021-11-05 14:33 UTC, mrojasabregu commented on spotify-service/src/main/java/com/pinapp/spotifyservice/service/ArtistService.java
> +    if(artists.stream().filter(a -> a.getIdArtist() == idArtist).findFirst().orElse(null) != null){
aca lo podes resolver con optional isPresent

2021-11-05 15:16 UTC, germansanz93 commented on spotify-service/src/main/java/com/pinapp/spotifyservice/controller/ArtistController.java
>  @RestController
Pero estaba haciendo referencia a esta clase:  https://docs.oracle.com/javase/8/docs/api/java/util/Arrays.html

2021-11-06 01:09 UTC, germansanz93 commented
Corregidas las observaciones..

2021-11-09 00:25 UTC, merged